services:
  - type: cron
    name: instagram-uploader
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python instagram_uploader.py
    schedule: "0 18 * * *"
