name: Instagram Video Upload

on:
  schedule:
    - cron: '0 18 * * *'  # Her gün saat 18:00 UTC'de çalışır
  workflow_dispatch:       # Manuel tetikleme için

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu çek
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: pip install -r requirements.txt

    - name: Instagram video yükle
      env:
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      run: |
        python instagram_uploader.py
